version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  myapp:
    image: myapp
    build:
      context: ./PlayerRegistration
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQSettings__Hostname=rabbitmq
      - RabbitMQSettings__Username=guest
      - RabbitMQSettings__Password=guest
      - RabbitMQSettings__ExchangeName=guest
      - RabbitMQSettings__RoutingKey=your_routing_key